### ISSUE TITLE
poor practice in example ?

### ISSUE THREAD

**Issue by the-Arioch** [slick/doc#4]
`def address = foreignKey("ADDRESS",addressId,addresses)(_.id)`

http://slick.lightbend.com/doc/3.2.0/sql-to-slick.html

this code uses magic constant "ADDRESS" for late binding, basicalyl this kills any type safety Scala is about

it should be `def address = foreignKey(Addresses,addressId,addresses)(_.id)`
if not possible, then like `def address = foreignKey(Addresses.SomePropertyOrFunction,addressId,addresses)(_.id)`

**Comment by the-Arioch** [comment]
as a sidenote - reopen https://github.com/slick/doc/issues/3

**Comment by the-Arioch** [comment]
> This allows to build libraries of queries, which re-use each other become much more maintainable

becomING or TO become

**Comment by d6y** [comment]
Hello @the-Arioch 

That `String` parameter is used to name the foreign key in the database, if you're using the Slick (if you're managing the schema with Slick). I don't think that affects the type safety, unless I don't  understand your comment.

**Comment by d6y** [comment]
Regarding #3 - good point. The code in master has been ported to a new documentation tool, but the content has not been published yet. The next release of the docs will fix that.

The source for the _becomING_ problem text is: https://github.com/slick/slick/blob/master/doc/src/sql-to-slick.md#slick-type-safe-composable-queries - if you want to make your correction against that, that'd be most welcome!  Hmm...also the start of the sentence doesn't really work either: _This allows US to build_, maybe.

**Comment by the-Arioch** [comment]
> That  String  parameter is used to name the foreign key in the database

to name an FK or the target table ?
cause if it names FK itself - the SQL entity "FOREIGN KEY" - then why bother, omit the parameter and let Slick derive it from the target table/view name

especially, since I can have three tables - A, B and C
and then both tables B and C could have an FK B-to-A and C-to-A

i would have to manually devise different string magic constants for them ? Why cannot Slick auto-gen the FK constraint names?

**Comment by the-Arioch** [comment]
Okay, let me put it another way.

From the help page:

```
 class People(tag: Tag) extends Table[Person](tag, "PERSON") {
 ...
    def address = foreignKey("ADDRESS",addressId,addresses)(_.id)
 ... 
 ...
 class Addresses(tag: Tag) extends Table[Address](tag, "ADDRESS") {
 ...
```

Here we see the magic constant "ADDRESS" happening twice.
What if i would change it in one line but not another ? How would it effect upon Slick internal work ?

**Comment by szeiger** [comment]
```
  /** Define a foreign key relationship.
    *
    * @param name The name of the foreign key in the database (only used when
    *             you define the database schema with Slick).
```

In the example:

```
    def address = foreignKey("ADDRESS",addressId,addresses)(_.id)
        ^^^^^^^               ^^^^^^^
```

These are the matching names (by convention). Note that this works exactly the same way as for column definitions. In particular, there is no situation where you have to repeat the same string constant multiple times in your schema definition.

With some macro hacks we could automatically derive column names. This hasn't been a high priority because usually you either generate the schema code from an existing database or you want full control over the names.

Control is less of a problem with constraint names because they are only used in DDL statements anyway. What makes it much harder for constraint names is the fact that they are not local to a table. Enumerating them (so they can be named in sequence) is brittle and always prepending the table name will easily run afoul of identifier length restrictions.

**Comment by nafg** [comment]
https://github.com/nafg/slick-additions has this functionality. See https://github.com/nafg/slick-additions#autoname
